# Generated by Django 6.0.3 on 2026-04-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_twofactorauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
