# Generated by Django 6.0.3 on 2026-04-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_progress', '0010_merge_20260414_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='badge_image_source',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='badge_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='lesson_highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='badge',
            name='skills_awarded',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
