# Generated by Django 6.0.3 on 2026-04-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_admin_seen_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='audience_type',
            field=models.CharField(choices=[('admins', 'Admins'), ('all_guides', 'All Guides'), ('selected_guides', 'Selected Guides')], default='all_guides', max_length=32),
        ),
        migrations.AddField(
            model_name='notification',
            name='tracking_type',
            field=models.CharField(choices=[('admin_shared', 'Shared admin read'), ('info_only', 'Info only'), ('user_read', 'User read tracking'), ('user_ack', 'User acknowledgement')], default='info_only', max_length=32),
        ),
    ]
