# Generated by Django 6.0.3 on 2026-04-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_related_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='show_in_header',
            field=models.BooleanField(default=True),
        ),
    ]
