# Generated by Django 6.0.3 on 2026-04-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_show_in_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='tracking_type',
            field=models.CharField(choices=[('admin_shared', 'Any admin can mark as read'), ('info_only', 'No response needed'), ('user_read', 'Read confirmation'), ('user_ack', 'User acknowledgement required')], default='info_only', max_length=32),
        ),
    ]
